[build]
  [[build.env]]
    name = "GOOGLE_NODE_RUN_SCRIPTS"
    value = "build"
  
  # Skip Next.js detection
  [[build.env]]
    name = "GOOGLE_SKIP_NEXTJS"
    value = "true"

[run]
  command = "node build/server.js"
